USE `sanguoshagaoshou`;

CREATE TABLE `soldier` (
  `UID` VARCHAR(12) NOT NULL,
  `PACKAGEID` INT(11) DEFAULT NULL,
  `NAME` VARCHAR(12) NOT NULL,
  `COUNTRYID` INT(11) NOT NULL,
  `SEX` CHAR(1) DEFAULT NULL,
  `BLOODPOINT` INT(11) DEFAULT NULL,
  `MAGICIDS` VARCHAR(12) DEFAULT NULL,
  PRIMARY KEY (`UID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;

CREATE TABLE `country` (
	`ID` INT (11) NOT NULL,
	`NAME` VARCHAR (2) NOT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;

CREATE TABLE `magic` (
	`ID` INT (11) NOT NULL,
	`NAME` VARCHAR (12) NOT NULL,
	`DESC` VARCHAR (256),
	PRIMARY KEY (`ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;

CREATE TABLE `CARDPACKAGE` (
	`ID` INT (11) NOT NULL,
	`NAME` VARCHAR (2) NOT NULL,
	PRIMARY KEY (`ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;